M48
; DRILL file {KiCad 9.0.4} date 2025-09-15T17:28:42-0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-09-15T17:28:42-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.4
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.300
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C1.020
%
G90
G05
T1
X137.0Y-94.0
T2
X146.058Y-90.96
X146.058Y-93.5
X146.058Y-96.04
M30
