M48
; DRILL file {KiCad 9.0.4} date 2025-09-15T17:28:42-0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-09-15T17:28:42-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
%
G90
G05
T1
X136.5Y-86.0
X136.5Y-101.0
X153.0Y-86.0
X153.0Y-101.0
M30
